@startuml

left to right direction

actor Administrador as Admin
actor Ejecutor as Ejec

rectangle "Sistema de Gestión de Tareas" {
    Admin -- (Crear tareas)
    Admin -- (Modificar tareas)
    Admin -- (Visualizar información de tareas)
    Admin -- (Visualizar registros de auditoría)
    Admin -- (Exportar datos a CSV)

    Ejec -- (Visualizar Tareas asignadas pendientes)
    Ejec -- (Marcar tareas como finalizada)
    Ejec -- (Marcar tareas como eliminada)
}

@enduml

