@startuml

left to right direction

actor Usuario as U

rectangle "Sistema de Gestión de Tareas" {
    U -- (Autenticación y Autorización)

    (Autenticación y Autorización) -- (Crear tareas)
    (Autenticación y Autorización) -- (Modificar tareas)
    (Autenticación y Autorización) -- (Visualizar información de tareas)
    (Autenticación y Autorización) -- (Visualizar seguimiento de tarea)
    (Autenticación y Autorización) -- (Exportar datos a CSV)

    rectangle "Tareas del Administrador" {
        (Crear tareas)
        (Modificar tareas)
        (Visualizar información de tareas)
        (Visualizar seguimiento de tarea)
        (Exportar datos a CSV)
    }

    rectangle "Tareas del Ejecutor" {
        (Visualizar Tareas asignadas pendientes)
        (Marcar tareas como finalizada)
        (Marcar tareas como eliminada)
    }
}

@enduml

